author: Yoshiki Kurihara <kurihara@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.64
license: unknown
name: Catalyst-Plugin-MobileAgent
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst: 5.3
  HTTP::MobileAgent: 0.22
  Test::More: 0
version: 0.03
